### !conda list
The !conda list command is used to display a list of all the packages installed in the current conda environment. This command is especially useful for checking which libraries are available, their versions.

In [1]:
!conda list

# packages in environment at C:\Users\Admin\anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2024.06             py312_mkl_2  
abseil-cpp                20211102.0           hd77b12b_0  
aext-assistant            4.0.15          py312haa95532_jl4_0  
aext-assistant-server     4.0.15          py312haa95532_0  
aext-core                 4.0.15          py312haa95532_jl4_0  
aext-core-server          4.0.15          py312haa95532_1  
aext-panels               4.0.15          py312haa95532_0  
aext-panels-server        4.0.15          py312haa95532_0  
aext-share-notebook       4.0.15          py312haa95532_0  
aext-share-notebook-server 4.0.15          py312haa95532_0  
aext-shared               4.0.15          py312haa95532_0  
aiobotocore               2.12.3          py312haa95532_0  
aiohttp                   3.9.5           py312h2bbff1b_0  
aioitertools              0.7.1              pyhd3eb1b0_0  
aiosignal                 1

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as nsn

# Task 1: Lists, Dictionaries, Tuples
- 1.1.  Create a list: nums = [3, 5, 7, 8, 12], make another list named ‘cubes’ and append the cubes of the given list ‘nums’ 
in this list and print it. 

In [10]:
# Define a list of numbers
nums = [3, 5, 7, 8, 12]

# Initialize an empty list to store the cubes of the numbers
cubes = []

# Loop through each number in the nums list
for num in nums:
    # Calculate the cube of the current number and append it to the cubes list
    cubes.append(num ** 3)

# Concatenate the original nums list with the cubes list
nums = nums + cubes

# Print the combined list which now contains both the original numbers and their cubes
print(nums)

[3, 5, 7, 8, 12, 27, 125, 343, 512, 1728]


1.2.  Create an empty dictionary: dict = {}, add the following data to the dictionary: ‘parrot’: 2, ‘goat’: 4, ‘spider’: 8, ‘crab’: 
10 as key value pairs. 

In [14]:
# Create an empty dictionary
dict = {}

# Add the specified key-value pairs to the dictionary
dict['parrot'] = 2
dict['goat'] = 4
dict['spider'] = 8
dict['crab'] = 10

# Print the resulting dictionary
print(dict)

{'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}


1.3.  Use the ‘items’ method to loop over the dictionary (dict) and print the animals and their corresponding legs. Sum 
the legs of each animal, and print the total at the end. 

In [17]:
# Initialize a variable to keep the sum of legs
total_legs = 0

# Use the items() method to loop over the dictionary
for animal, legs in dict.items():
    # Print the animal and its corresponding number of legs
    print(f"{animal}: {legs} legs")
    
    # Add the number of legs to the total
    total_legs += legs

# Print the total number of legs
print(f"Total legs: {total_legs}")

parrot: 2 legs
goat: 4 legs
spider: 8 legs
crab: 10 legs
Total legs: 24


1.4.  Create a tuple: A = (3, 9, 4, [5, 6]), change the value in the list from ‘5’ to ‘8’. 

In [20]:
# Create the tuple with a list inside
A = (3, 9, 4, [5, 6])

# Access the list inside the tuple and change the value 5 to 8
A[3][0] = 8

# Print the modified tuple
print(A)

(3, 9, 4, [8, 6])


1.5.  Delete the tuple A. 

In [23]:
# Delete the tuple
del A

1.6.  Create another tuple: B = (‘a’, ‘p’, ‘p’, ‘l’, ‘e’), print the number of occurrences of ‘p’ in the tuple. 

In [26]:
# Create the tuple
B = ('a', 'p', 'p', 'l', 'e')

# Count the number of occurrences of 'p' in the tuple
count_p = B.count('p')

# Print the count
print(count_p)

2


1.7.  Print the index of ‘l’ in the tuple.

In [29]:
# Find the index of 'l' in the tuple
index_l = B.index('l')

# Print the index
print(index_l)

3


# Task 2: Numpy 
Use built-in functions of numpy library to complete this task. 
List of functions available here (https://numpy.org/doc/1.19/genindex.html)

In [40]:
A = [[1, 2, 3, 4], 
     [5, 6, 7, 8], 
     [9, 10, 11, 12]]
z = np.array([1,0,1])

2.1  Convert matrix A into numpy array 

In [43]:
A = np.array(A)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

2.2  Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2. Store it in b which is a numpy 
array of shape (2, 2). 

2.3  Create an empty matrix ‘C’ with the same shape as ‘A’. 

In [46]:
# Use slicing to extract the subarray of the first 2 rows and columns 1 and 2
b = A[:2, 1:3]

# Print the subarray
print(b)

[[2 3]
 [6 7]]


2.3  Create an empty matrix ‘C’ with the same shape as ‘A’. 

In [48]:
# Create an empty matrix C with the same shape as A
C = np.empty(A.shape)

# Print the empty matrix C
print(C)

[[1.01855798e-312 1.10343781e-312 1.01855798e-312 9.54898106e-313]
 [1.08221785e-312 1.03977794e-312 1.23075756e-312 1.16709769e-312]
 [1.01855798e-312 9.76118064e-313 1.20953760e-312 1.90979621e-312]]


2.4  Add the vector z to each column of the matrix ‘A’ with an explicit loop and store it in ‘C’. 

In [54]:
# Add the vector z to each column of A using an explicit loop
for col in range(A.shape[1]):
    C[:, col] = A[:, col] + z

# Print the resulting matrix C
print(C)

[[ 2.  3.  4.  5.]
 [ 5.  6.  7.  8.]
 [10. 11. 12. 13.]]


Create the following

In [62]:
X = np.array([[1,2],[3,4]]) 
Y = np.array([[5,6],[7,8]]) 
v = np.array([9,10]) 

2.5  Add and print the matrices X and Y.

In [65]:
# Add the matrices X and Y
addition = X + Y

# Print the result
print("Addition of X and Y:")
print(addition)

Addition of X and Y:
[[ 6  8]
 [10 12]]


2.6  Multiply and print the matrices X and Y. 

In [68]:
# Multiply the matrices X and Y
multiplication = np.dot(X, Y)

# Print the result
print("\nMultiplication of X and Y:")
print(multiplication)


Multiplication of X and Y:
[[19 22]
 [43 50]]


2.7  Compute and print the element wise square root of matrix Y.

In [71]:
# Compute the element-wise square root of matrix Y
sqrt_Y = np.sqrt(Y)

# Print the result
print("\nElement-wise square root of Y:")
print(sqrt_Y)


Element-wise square root of Y:
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


2.8  Compute and print the dot product of the matrix X and vector v. 

In [74]:
# Compute the dot product of matrix X and vector v
dot_product = np.dot(X, v)

# Print the result
print("\nDot product of X and v:")
print(dot_product)


Dot product of X and v:
[29 67]


2.9  Compute and print the sum of each column of X. 

In [77]:
# Compute the sum of each column of X
column_sum = np.sum(X, axis=0)

# Print the result
print("\nSum of each column of X:")
print(column_sum)


Sum of each column of X:
[4 6]


# Task 3: Functions and Loops 

3.1  Create a function ‘Compute’ that takes two arguments, distance and time, and use it to calculate velocity. 

In [81]:
# Define the function Compute
def Compute(distance, time):
    # Calculate velocity
    velocity = distance / time
    return velocity

# Example usage of the function
distance = 100  # Example distance in meters
time = 20       # Example time in seconds

# Calculate velocity using the Compute function
velocity = Compute(distance, time)

# Print the result
print(f"Velocity: {velocity} m/s")


Velocity: 5.0 m/s


3.2 Make a list named ‘even_num’ that contains all even numbers up till 12. Create a function ‘mult’ that takes the list 
‘even_num’  as an argument and calculates the products of all entries using a for loop. 

In [84]:
# Create a list named even_num that contains all even numbers up to 12
even_num = [2, 4, 6, 8, 10, 12]

# Define the function mult that calculates the product of all entries in the list
def mult(numbers):
    product = 1  # Initialize the product variable
    for num in numbers:  # Loop through each number in the list
        product *= num  # Multiply each number with the current product
    return product

# Calculate the product of all entries in the list even_num
result = mult(even_num)

# Print the result
print(f"The product of all entries in even_num is: {result}")


The product of all entries in even_num is: 46080


# Task 4: Pandas 
Create a Pandas dataframe named ‘pd’ that contains 5 rows and 4 columns, similar to the one given below:

In [90]:
# Creating the DataFrame
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

# Create the dataframe named 'pd'
df = pd.DataFrame(data)

4.1  Print only the first two rows of the dataframe. 

In [92]:
# Display the data frame
print(df)

   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


4.2  Print the second column. 

In [95]:
# Print the second column 'C2'
print(df['C2'])

0    6
1    7
2    5
3    4
4    8
Name: C2, dtype: int64


4.3  Change the name of the third column from ‘C3’ to ‘B3’. 

In [98]:
# Rename the third column from 'C3' to 'B3'
df = df.rename(columns={'C3': 'B3'})

# Display the updated dataframe
print(df)

   C1  C2  B3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


4.4  Add a new column to the dataframe and name it ‘Sum’. 

In [101]:
# Add a new column 'Sum' which is the sum of each row
df['Sum'] = df.sum(axis=1)

# Display the updated dataframe
print(df)


   C1  C2  B3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


4.5  Sum the entries of each row and add the result in the column ‘Sum’. 

In [103]:
# Add a new column 'Sum' that contains the sum of each row's entries
df['Sum'] = df.sum(axis=1)

# Display the updated dataframe
print(df)

   C1  C2  B3  C4  Sum
0   1   6   7   7   42
1   2   7   9   5   46
2   3   5   8   2   36
3   5   4   6   8   46
4   5   8   5   8   52


4.6 Read CSV file named ‘hello_sample.csv’ (the file is available in the class Google Drive shared folder) into a Pandas 
dataframe. 

In [111]:
import pandas as pd

# Reading the CSV file into a DataFrame
df_csv = pd.read_csv('hello_sample.csv')


4.7  Print complete dataframe.

In [114]:
# Display the dataframe
print(df_csv)

    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66


4.8  Print only bottom 2 records of the dataframe. 

In [117]:
# Print the bottom 2 records of the DataFrame
print(df.tail(2))

   C1  C2  B3  C4  Sum
3   5   4   6   8   46
4   5   8   5   8   52


4.9  Print information about the dataframe. 

In [120]:
# Print information about the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      5 non-null      int64
 1   C2      5 non-null      int64
 2   B3      5 non-null      int64
 3   C4      5 non-null      int64
 4   Sum     5 non-null      int64
dtypes: int64(5)
memory usage: 332.0 bytes


4.10  Print shape (rows x columns) of the dataframe. 

In [123]:
# Print information about the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      5 non-null      int64
 1   C2      5 non-null      int64
 2   B3      5 non-null      int64
 3   C4      5 non-null      int64
 4   Sum     5 non-null      int64
dtypes: int64(5)
memory usage: 332.0 bytes


4.11  Sort the data of the dataFrame using column ‘Weight’.

In [129]:
# Sort the DataFrame by the 'Weight' column
df_sorted = df.sort_values(by='C2')

# Display the sorted DataFrame
print(df_sorted)

   C1  C2  B3  C4  Sum
3   5   4   6   8   46
2   3   5   8   2   36
0   1   6   7   7   42
1   2   7   9   5   46
4   5   8   5   8   52


4.12  Use isnull() and dropna() methods of the Pandas dataframe and see if they produce any changes.

In [134]:
# Drop rows with any missing values
df_cleaned = df.dropna()

# Display the DataFrame after dropping rows with null values
print(df_cleaned)

   C1  C2  B3  C4  Sum
0   1   6   7   7   42
1   2   7   9   5   46
2   3   5   8   2   36
3   5   4   6   8   46
4   5   8   5   8   52
